name: Deploy main branch
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install serverless-python-requirements serverless-iam-roles-per-function
    #- run: npm ci
    - name: serverless deploy
      uses: jackdcasey/github-action@python3.8-nodejs13
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SERVERLESS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVERLESS_SECRET_ACCESS_KEY }}
